# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
notifications:
  email: true
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/kalmarek/Groups.jl")); Pkg.build(); Pkg.test(coverage=true);'
  - julia --color=yes -e "if VERSION < v\"0.7.0-DEV.5183\"; cd(Pkg.dir(\"${JL_PKG}\")); else using Pkg; end; Pkg.add(\"Coverage\"); using Coverage; Codecov.submit(process_folder())"

codecov: true
