# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.4
  - 1.5
  - nightly
notifications:
  email: true
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

script:
  - julia -e 'using Pkg; pkg"add https://github.com/kalmarek/Groups.jl"; Pkg.build(); Pkg.test(coverage=true);'

codecov: true
