# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly
notifications:
  email: true
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

after_success:
  # push coverage results to Coveralls
   - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
